language: c

os:
  - linux
  - osx

sudo: false

notifications:
  email: false

env:
  global:
    - CONDA_CHANNELS="conda-forge"
    - CONDA_DEPENDENCIES="astropy coveralls cython healpy pillow"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - python setup.py sdist
  - cd dist && pip install *.tar.gz --verbose && cd ..
  - py.test --cov toasty toasty

after_success:
  - coveralls
