# Main build jobs for CI/CD on Azure Pipelines.

parameters:
- name: builds
  type: object
  default:

  - name: linux_37
    vmImage: ubuntu-20.04
    vars:
      PYTHON_SERIES: "3.7"

  - name: linux_38
    vmImage: ubuntu-20.04
    vars:
      PYTHON_SERIES: "3.8"

  - name: macos_37
    vmImage: macos-10.15
    vars:
      PYTHON_SERIES: "3.7"

  - name: macos_38
    vmImage: macos-10.15
    vars:
      PYTHON_SERIES: "3.8"

  - name: windows_37
    vmImage: windows-2019
    vars:
      PYTHON_SERIES: "3.7"

  - name: windows_38
    vmImage: windows-2019
    vars:
      PYTHON_SERIES: "3.8"

jobs:
- ${{ each build in parameters.builds }}:
  - job: ${{ format('build_{0}', build.name) }}
    pool:
      vmImage: ${{ build.vmImage }}
    variables:
      ${{ insert }}: ${{ build.vars }}
    steps:

    - template: azure-job-setup.yml
      parameters:
        setupBuild: true

    - bash: |
        set -euo pipefail
        source activate-conda.sh
        set -x
        \conda create -y -n build setuptools pip python="$PYTHON_SERIES"
        conda activate build
        pip install $BASH_WORKSPACE/sdist/*.tar.gz
      displayName: Install from sdist

    - bash: |
        set -euo pipefail
        source activate-conda.sh
        conda activate build
        set -x

        if [[ $AGENT_OS == Windows_NT ]] ; then
          \conda install -y astropy pytest
        else
          \conda install -y astropy healpy pytest
        fi

        pytest --pyargs toasty
      displayName: Test

- job: coverage
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      set -x
      \conda create -y -n build setuptools pip python=3.8
      conda activate build
      pip install $BASH_WORKSPACE/sdist/*.tar.gz
    displayName: Install from sdist

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      \conda install -y \
        cython \
        filelock \
        healpy \
        numpy \
        openexr-python \
        pillow \
        pytest-cov \
        pyyaml \
        tqdm
      pip install wwt_data_formats
      pip install -e .
      pytest --cov-report=xml --cov=toasty toasty
    displayName: Test with coverage

  - bash: bash <(curl -s https://codecov.io/bash)
    displayName: Upload coverage results

- job: docs
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      set -x
      \conda create -y -n build setuptools pip python=3.8
      conda activate build
      pip install $BASH_WORKSPACE/sdist/*.tar.gz
    displayName: Install from sdist

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      \conda install -y astropy numpydoc sphinx sphinx-automodapi
      pip install astropy-sphinx-theme
      cd docs
      make html
      make linkcheck
    displayName: Build docs
